CREATE TABLE SICREDI.PAUTA (
	ID NUMBER(10),
	TITULO VARCHAR2(150),
	DATA_CRIACAO DATE,
	STATUS NUMBER(1,2),
	DATA_HORA_INICIO_VOTACAO date,
	DATA_HORA_FIM_VOTACAO date
);

ALTER TABLE SICREDI.PAUTA ADD (
  CONSTRAINT PAUTA_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SICREDI.PAUTA_SEQ START WITH 1;