CREATE TABLE PAUTA (
	ID NUMBER(10),
	TITULO VARCHAR2(150),
	DATA_CRIACAO DATE,
	STATUS NUMBER(1,2),
	DATA_HORA_INICIO_VOTACAO date,
	DATA_HORA_FIM_VOTACAO date,
	VOTOS_A_FAVOR NUMBER(1,10),
	VOTOS_CONTRA NUMBER(1,10)
);

ALTER TABLE PAUTA ADD (
  CONSTRAINT PAUTA_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE PAUTA_SEQ START WITH 1;