CREATE TABLE SICREDI.VOTO (
	ID NUMBER(10),
	VOTO_ASSOCIADO NUMBER(1,2),
	DATA_CRIACAO DATE,
	ID_PAUTA NUMBER(10),
	CPF_ASSOCIADO
);

ALTER TABLE SICREDI.VOTO ADD (
  CONSTRAINT VOTO_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SICREDI.VOTO_SEQ START WITH 1;